import { docTeachData } from "../docTeach/data";

export const moduleData = [
  {
    id: "1",
    years: [2, 3, 4],
    code: "MATH101",
    hours: 3,
    doctor: "1",
    teacher: "2",
  },
  {
    id: "2",
    years: [2, 3, 4],
    code: "MATH102",
    hours: 3,
    doctor: "2",
    teacher: "4",
  },
  {
    id: "3",
    years: [2, 3, 4],
    code: "MATH103",
    hours: 3,
    doctor: "3",
    teacher: "3",
  },
  {
    id: "4",
    years: [2, 3, 4],
    code: "MATH104",
    hours: 3,
    doctor: "1",
    teacher: "1",
  },
  {
    id: "5",
    years: [2, 3, 4],
    code: "MATH105",
    hours: 3,
    doctor: "2",
    teacher: "2",
  },
  {
    id: "6",
    years: [2, 3, 4],
    code: "MATH106",
    hours: 3,
    doctor: "3",
    teacher: "4",
  },
  {
    id: "7",
    years: [2, 3, 4],
    code: "MATH107",
    hours: 3,
    doctor: "1",
    teacher: "3",
  },
  {
    id: "8",
    years: [2, 3, 4],
    code: "MATH108",
    hours: 3,
    doctor: "2",
    teacher: "1",
  },
  {
    id: "9",
    years: [2, 3, 4],
    code: "MATH109",
    hours: 3,
    doctor: "3",
    teacher: "2",
  },
  {
    id: "10",
    years: [2, 3, 4],
    code: "MATH110",
    hours: 3,
    doctor: "1",
    teacher: "4",
  },
  {
    id: "11",
    years: [2, 3, 4],
    code: "MATH111",
    hours: 3,
    doctor: "2",
    teacher: "3",
  },
  {
    id: "12",
    years: [2, 3, 4],
    code: "MATH112",
    hours: 3,
    doctor: "3",
    teacher: "1",
  },
  {
    id: "13",
    years: [2, 3, 4],
    code: "MATH113",
    hours: 3,
    doctor: "1",
    teacher: "2",
  },
  {
    id: "14",
    years: [2, 3, 4],
    code: "MATH114",
    hours: 3,
    doctor: "2",
    teacher: "4",
  },
  {
    id: "15",
    years: [2, 3, 4],
    code: "MATH115",
    hours: 3,
    doctor: "3",
    teacher: "3",
  },
  {
    id: "16",
    years: [2, 3, 4],
    code: "MATH116",
    hours: 3,
    doctor: "1",
    teacher: "4",
  },
];
